# Generated by Django 6.0.2 on 2026-02-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='register',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
