# Generated by Django 6.0.2 on 2026-02-24 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Ажилтан', max_length=150),
        ),
    ]
