# Generated by Django 6.0.2 on 2026-02-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_create_default_role_groups'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptresponse',
            name='selected_answer',
        ),
        migrations.AddField(
            model_name='exam',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='exams', to='employees.department'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('official', 'Албан ёсны'), ('practice', 'Дадлагын')], default='official', max_length=16),
        ),
        migrations.AddField(
            model_name='exam',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='exams', to='employees.position'),
        ),
        migrations.AddField(
            model_name='exam',
            name='target_type',
            field=models.CharField(choices=[('organization_wide', 'Бүх ажилтан'), ('department', 'Хэлтсийн'), ('position', 'Албан тушаалын')], default='organization_wide', max_length=32),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='exam_questions/'),
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pass_score',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='attemptresponse',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt_responses', to='exams.choice'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
