# Generated by Django 6.0.2 on 2026-02-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_attemptresponse_selected_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('official', 'Албан ёсны'), ('practice', 'Жишиг')], default='official', max_length=16),
        ),
    ]
