# Generated by Django 6.0.2 on 2026-02-24 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_create_default_role_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('notice_type', models.CharField(choices=[('organization_wide', 'Бүх ажилтан'), ('department', 'Хэлтсийн'), ('position', 'Албан тушаалын'), ('specific_employee', 'Тухайлсан ажилтан')], max_length=32)),
                ('requires_acknowledgement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_notices', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='notices', to='employees.department')),
                ('employees', models.ManyToManyField(blank=True, related_name='notices', to='employees.employee')),
                ('positions', models.ManyToManyField(blank=True, related_name='notices', to='employees.position')),
            ],
            options={
                'verbose_name': 'Мэдэгдэл',
                'verbose_name_plural': 'Мэдэгдлүүд',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NoticeRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_reads', to='employees.employee')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notices.notice')),
            ],
            options={
                'verbose_name': 'Мэдэгдэл уншилт',
                'verbose_name_plural': 'Мэдэгдэл уншилтууд',
                'ordering': ('-read_at',),
                'constraints': [models.UniqueConstraint(fields=('employee', 'notice'), name='unique_employee_notice_read')],
            },
        ),
    ]
