# Generated by Django 6.0.2 on 2026-02-24 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_create_default_role_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('training_type', models.CharField(choices=[('organization_wide', 'Бүх ажилтан'), ('department', 'Хэлтсийн'), ('position', 'Албан тушаалын'), ('specific_employee', 'Тухайлсан ажилтан')], max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trainer_name', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_trainings', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='trainings', to='employees.department')),
                ('employees', models.ManyToManyField(blank=True, related_name='target_trainings', to='employees.employee')),
                ('positions', models.ManyToManyField(blank=True, related_name='trainings', to='employees.position')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrainingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('image', 'Зураг'), ('pdf', 'PDF'), ('ppt', 'PPT'), ('doc', 'DOC'), ('video', 'Видео'), ('text', 'Текст')], max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='training_materials/')),
                ('text_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='trainings.training')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrainingParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Хуваарилагдсан'), ('attended', 'Суусан'), ('completed', 'Дууссан'), ('failed', 'Тэнцээгүй')], default='assigned', max_length=16)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_participations', to='employees.employee')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='trainings.training')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('employee', 'training'), name='unique_employee_training_participation')],
            },
        ),
    ]
