# Generated by Django 6.0.2 on 2026-02-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmaterial',
            name='material_type',
            field=models.CharField(choices=[('image', 'Зураг'), ('pdf', 'PDF'), ('text', 'Текст')], max_length=16),
        ),
    ]
