# Generated by Django 6.0.2 on 2026-02-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_register'),
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='validity_days',
            field=models.PositiveIntegerField(default=365, help_text='Зааварчилгаа хэдэн хоног хүчинтэй байх хугацаа'),
        ),
        migrations.CreateModel(
            name='InstructionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField()),
                ('valid_until', models.DateField(blank=True)),
                ('trainer_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_records', to='employees.employee')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='instructions.instruction')),
            ],
            options={
                'ordering': ('valid_until', '-created_at'),
                'unique_together': {('employee', 'instruction', 'completed_on')},
            },
        ),
    ]
