# Generated by Django 6.0.2 on 2026-02-24 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_create_default_role_groups'),
        ('instructions', '0002_instruction_validity_days_instructionrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='instructionrecord',
            options={'ordering': ('next_due_date', '-created_at')},
        ),
        migrations.AlterUniqueTogether(
            name='instructionrecord',
            unique_together={('employee', 'instruction')},
        ),
        migrations.AddField(
            model_name='instruction',
            name='instruction_type',
            field=models.CharField(choices=[('organization', 'Байгууллагын нийтлэг'), ('department', 'Хэлтсийн'), ('position', 'Албан тушаалын')], default='organization', max_length=32),
        ),
        migrations.AddField(
            model_name='instructionrecord',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructionrecord',
            name='acknowledged_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructionrecord',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructionrecord',
            name='next_due_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.RemoveField(
            model_name='instructionrecord',
            name='completed_on',
        ),
        migrations.RemoveField(
            model_name='instructionrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='instructionrecord',
            name='trainer_name',
        ),
        migrations.RemoveField(
            model_name='instructionrecord',
            name='valid_until',
        ),
    ]
